### ISSUE TITLE
点击按钮后弹窗迟钝

### ISSUE THREAD

**Issue by paulsmithgood** [energye/energy#19]
作者您好:
今天在实现的过程中发现了一个问题，我要用到的功能是:在点击浏览器上的按钮后会生成一个pdf文件，然后随之会调用打印机进行打印机。
我在用浏览器进行操作时点击后会迅速的唤醒，而用golang内嵌的网页时速度就会比较慢了，要等待一会才出来，有时候点击了按钮后就干脆不唤醒打印机界面了。
想了解一下我遇到了这个问题该怎么去处理优化。
非常感谢您的开源让我的工作得到了帮助，期待您的回复!

**Comment by sxmxta** [comment]
你好，根据你的描述，我理解的不是很清楚，你可以贴部分操作的关键代码，和操作截图来判断。
1. 根据你的标题，是弹窗迟钝，看起来好像是html渲染慢，针对这点你可以开启GPU加速，默认energy未开启GPU加速。
```go
app := cef.NewApplication()
app.SetEnableGPU(true) // open GPU
```
2. 根据你的内容描述，如果使用CEF的预览打印，这里是CEF处理，我没发现这种弹出预览打印窗口慢的问题。

另外我没有打印机无法测试打印。
你使用的是哪个版本？
