### ISSUE TITLE
Isolate CEF only functionality in a standalone go module

### ISSUE THREAD

**Issue by devgodxxx** [energye/energy#24]
It would be useful if you could isolate the CEF module that has bindings to the cef, so it can be used standalone.

Currently every other implementation in Go is out of date and abandoned.

Thank you for your efforts.

**Comment by sxmxta** [comment]
Hello, I don't understand what you mean.
Are you saying that only CEF is encapsulated in Go?
If that's the case, it's contrary to my original intention.
The bottom layer of Energy is developed based on the LCL component library, which includes the CEF component, as well as other webview2, webkit, etc.
Moreover, Energy will support LCL, CEF, webview2, and webkit in the next version, providing a wider range of options.

**Comment by sxmxta** [comment]
It is worth noting that LCL is a very powerful cross platform native UI component library.


If you want to use only CEF instead of other components, it won't affect your usage either. The dynamic library may be slightly larger, and the execution files for Go slightly larger.
