### ISSUE TITLE
[bug] a fatal error when create a new browser window

### ISSUE THREAD

**Issue by JSchmidt63** [energye/energy#26]
CEF 118
Windows 11

go.mod:
```go
module main

go 1.22.0

require (
	github.com/dustin/go-humanize v1.0.1
	github.com/energye/energy/v2 v2.3.6
)

require (
	github.com/energye/golcl v1.0.10 // indirect
	github.com/godbus/dbus/v5 v5.1.0 // indirect
	github.com/tevino/abool v0.0.0-20220530134649-2bfc934cb23c // indirect
	golang.org/x/sys v0.17.0 // indirect
)
```

```go
package main

import (
	"fmt"
	"runtime"

	"github.com/dustin/go-humanize"
	"github.com/energye/energy/v2/cef"
	"github.com/energye/energy/v2/logger"
	"github.com/energye/energy/v2/consts"

)

const BrowserVersion = "118"

func main() {
	logger.SetEnable(true)
	logger.SetLevel(logger.CefLog_Debug) 
	fmt.Printf("\nVersion:%s", runtime.Version())
	fmt.Printf("\nCompiler:%s", runtime.Compiler)
	fmt.Printf("\nNo. of CPU:%v\n", runtime.NumCPU())
	fmt.Printf("\nGOOS:%s", runtime.GOOS)
	fmt.Printf("\nGOARCH:%s", runtime.GOARCH)
	fmt.Printf("\nGOROOT:%s\n", runtime.GOROOT())
	fmt.Printf("\nBrowserVersion:%s\n", BrowserVersion)

	//global initialization must be called by every application, then create application
	cef.GlobalInit(nil, nil)
	cefApp := cef.NewApplication()
	cefApp.SetEnableGPU(true)
	cefApp.SetAllowInsecureLocalhost(true)
	cefApp.SetLocale(consts.LANGUAGE_en_US)


	cef.BrowserWindow.Config.EnableCenterWindow= false
	cef.BrowserWindow.Config.X=1
	cef.BrowserWindow.Config.Y=1
	cef.BrowserWindow.Config.Height= 900
	cef.BrowserWindow.Config.Width= 1800
	cef.BrowserWindow.Config.ChromiumConfig().SetEnableMenu(true) //Enable right-click menu
	cef.BrowserWindow.Config.ChromiumConfig().SetEnableDevTools(true) //Enabling Developer Tools

	fmt.Printf("ChromeBuild:%s\n", cefApp.ChromeVersion())
	fmt.Printf("LibVersion:%s\n", cefApp.LibVersion())
	fmt.Printf("LibCefVersion:%s\n", cefApp.LibCefVersion())
	fmt.Printf("TotalSystemMemory:%s\n", humanize.Bytes(cefApp.TotalSystemMemory()))
	fmt.Printf("UsedMemory::%s\n", humanize.Bytes(cefApp.UsedMemory()))

	// Set the i18n resource loading method here, use the built-in to exe method here.
	//i18n.SetLocalFS(&resources, "resources")
	//i18n.Switch(consts.LANGUAGE_en_US)

	//specify a URL address, or a local html file directory
	cef.BrowserWindow.Config.Url = "https://html.com/attributes/a-target/"
	cef.BrowserWindow.Config.Title = "ENERGY 2.3.6 Test"

	//run application
	cef.Run(cefApp)
}
```

click at the link at the page 
Code Example
<a href="/" target="_blank">The home page will open in another tab.</a>

And you get some error:

PS C:\Users\JS\Desktop\VSCode\chromium\chromium-118 2-3-6\examples> ./main.exe

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
UsedMemory::14 MB
[ENERGY-Debug] 2024/02/27 13:41:36 new browser channel for IPC Sock C:\Users\JS\AppData\Local\Temp\energy.sock
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe,  process start

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
UsedMemory::14 MB

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe, gpu-process process start
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
UsedMemory::15 MB

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118
UsedMemory::15 MB

Version:go1.22.0
Compiler:gc
No. of CPU:12

GOOS:windows
GOARCH:amd64
GOROOT:C:\Program Files\Go

BrowserVersion:118
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
The specified procedure could not be found. CEFAppConfig_SpecificVersion
ChromeBuild:118.0.5993.119
LibVersion:
LibCefVersion:118.7.1.0
TotalSystemMemory:34 GB
UsedMemory::15 MB
UsedMemory::15 MB
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe, utility process start
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe, utility process start
[ENERGY-Debug] 2024/02/27 13:41:36 new render channel for IPC Sock C:\Users\JS\AppData\Local\Temp\energy.sock
[ENERGY-Debug] 2024/02/27 13:41:36 new render channel for IPC Sock C:\Users\JS\AppData\Local\Temp\energy.sock
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe, renderer process start
[ENERGY-Info] 2024/02/27 13:41:36 IPC browser on channel channelId: 1709037696428
[ENERGY-Info] 2024/02/27 13:41:36 IPC browser on channel channelId: 1709037696428
[ENERGY-Debug] 2024/02/27 13:41:36 application single exe, renderer process start
[ENERGY-Info] 2024/02/27 13:41:36 IPC browser on channel channelId: 21474836481
[ENERGY-Debug] 2024/02/27 13:41:36 IPC browser channel remove channelId: 1709037696428
[ENERGY-Info] 2024/02/27 13:41:37 IPC browser on channel channelId: 21474836484
[ENERGY-Debug] 2024/02/27 13:41:37 IPC browser channel remove channelId: 21474836481
[ENERGY-Info] 2024/02/27 13:41:37 IPC browser on channel channelId: 21474836485
[ENERGY-Debug] 2024/02/27 13:41:37 IPC browser channel remove channelId: 21474836484
[ENERGY-Info] 2024/02/27 13:41:37 IPC browser on channel channelId: 21474836486
[ENERGY-Debug] 2024/02/27 13:41:37 IPC browser channel remove channelId: 21474836485
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x59a9ba]

goroutine 17 gp=0xc000050380 m=1 mp=0xc00005c008 [running, locked to thread]:
runtime.throw({0x797fc3?, 0x30?})
        C:/Program Files/Go/src/runtime/panic.go:1023 +0x65 fp=0xc00002c100 sp=0xc00002c0d0 pc=0x1cd2a5
runtime.sigpanic()
        C:/Program Files/Go/src/runtime/signal_windows.go:414 +0xd0 fp=0xc00002c148 sp=0xc00002c100 pc=0x1e2d50
github.com/energye/energy/v2/cef.(*tCefPopupFeaturesPtr).convert.func2(...)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/cef/types_cef_ptr.go:317
github.com/energye/energy/v2/cef.(*tCefPopupFeaturesPtr).convert(0x22d6a9484e0?)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/cef/types_cef_ptr.go:330 +0x5a fp=0xc00002c1b8 sp=0xc00002c148 pc=0x59a9ba
github.com/energye/energy/v2/cef.init.4.func2({0x723440?, 0xc00024e018}, 0xc000296be0)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/cef/chromium_event.go:893 +0x40ba fp=0xc00002d1c8 sp=0xc00002c1b8 pc=0x567ffa
github.com/energye/golcl/lcl.eventCallbackProc(0xc000212cf0?, 0x6c6fbfd638, 0x2?)
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/callbackevent.go:94 +0xe2 fp=0xc00002da50 sp=0xc00002d1c8 pc=0x3b2082
runtime.call32(0x0, 0x838378, 0xc00002dab0, 0x0, 0x0, 0x18, 0xc00002dce0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:771 +0x48 fp=0xc00002da80 sp=0xc00002da50 pc=0x1feb08
runtime.callbackWrap(0x6c6fbfd4d0)
        C:/Program Files/Go/src/runtime/syscall_windows.go:396 +0x205 fp=0xc00002de58 sp=0xc00002da80 pc=0x1eb745
runtime.cgocallbackg1(0x1eb540, 0x6c6fbfd4d0, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:403 +0x2b1 fp=0xc00002df18 sp=0xc00002de58 pc=0x1994b1
runtime.cgocallbackg(0x1eb540, 0x6c6fbfd4d0, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:322 +0x133 fp=0xc00002df90 sp=0xc00002df18 pc=0x199153
runtime.cgocallbackg(0x1eb540, 0x6c6fbfd4d0, 0x0)
        <autogenerated>:1 +0x2e fp=0xc00002dfb8 sp=0xc00002df90 pc=0x2050ee
runtime.cgocallback(0x0, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:1079 +0xec fp=0xc00002dfe0 sp=0xc00002dfb8 pc=0x20030c
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00002dfe8 sp=0xc00002dfe0 pc=0x200561

goroutine 1 gp=0xc000050000 m=0 mp=0xeccba0 [syscall, locked to thread]:
runtime.cgocall(0x201d20, 0xeccfa0)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00007db08 sp=0xc00007dad0 pc=0x198d5e
syscall.SyscallN(0x110003810?, {0xc00007dba0?, 0x3?, 0xf?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc00007db80 sp=0xc00007db08 pc=0x1fd427
syscall.Syscall(0x110000000?, 0x110003810?, 0xc00007dc38?, 0x2d2f49?, 0x110000000?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc00007dbc8 sp=0xc00007db80 pc=0x1fd175
github.com/energye/golcl/lcl/api/dllimports.SyscallN(0xc000210000?, {0xc00007dca8?, 0x8383a0?, 0x838200?})
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/api/dllimports/dll_windows.go:45 +0x65 fp=0xc00007dc48 sp=0xc00007dbc8 pc=0x2d2ba5
github.com/energye/golcl/lcl/api/dllimports.ProcAddr.Call(...)
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/api/dllimports/dll_windows.go:33
github.com/energye/golcl/lcl/api.defSyscallN(0x0?, {0xc00007dca8, 0x1, 0x1})
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/api/dylib.go:75 +0x65 fp=0xc00007dc80 sp=0xc00007dc48 pc=0x32b0c5
github.com/energye/golcl/lcl/api.Application_Run(0xc000121188?)
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/api/importdef.go:39 +0x50 fp=0xc00007dcc8 sp=0xc00007dc80 pc=0x3375f0
github.com/energye/golcl/lcl.(*TApplication).Run(...)
        C:/Users/JS/go/pkg/mod/github.com/energye/golcl@v1.0.10/lcl/applicationdef.go:95
github.com/energye/energy/v2/cef.(*browserWindow).createFormAndRun(0xea2420)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/cef/browser_main_window.go:84 +0x19d fp=0xc00007dd28 sp=0xc00007dcc8 pc=0x552c1d
github.com/energye/energy/v2/cef.Run(0xc00006a380)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/cef/application_run.go:106 +0x133 fp=0xc00007dd50 sp=0xc00007dd28 pc=0x551673
main.main()
        C:/Users/JS/Desktop/VSCode/chromium/chromium-118 2-3-6/examples/main.go:63 +0x897 fp=0xc00007df50 sp=0xc00007dd50 pc=0x6740b7
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:271 +0x28b fp=0xc00007dfe0 sp=0xc00007df50 pc=0x1cfbcb
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x200561

goroutine 2 gp=0xc000050700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc000053fa8 sp=0xc000053f88 pc=0x1cffce
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:408
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:326 +0xb8 fp=0xc000053fe0 sp=0xc000053fa8 pc=0x1cfe58
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x200561
created by runtime.init.6 in goroutine 1
        C:/Program Files/Go/src/runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000050a80 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc000055f80 sp=0xc000055f60 pc=0x1cffce
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:408
runtime.bgsweep(0xc000060000)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x94 fp=0xc000055fc8 sp=0xc000055f80 pc=0x1ba214
runtime.gcenable.gowrap1()
        C:/Program Files/Go/src/runtime/mgc.go:203 +0x25 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x1aeb25
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x200561
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000050c40 m=nil [GC scavenge wait]:
runtime.gopark(0xc000060000?, 0x9b69d0?, 0x1?, 0x0?, 0xc000050c40?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc000067f78 sp=0xc000067f58 pc=0x1cffce
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:408
runtime.(*scavengerState).park(0xecbe80)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000067fa8 sp=0xc000067f78 pc=0x1b7c09
runtime.bgscavenge(0xc000060000)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000067fc8 sp=0xc000067fa8 pc=0x1b819c
runtime.gcenable.gowrap2()
        C:/Program Files/Go/src/runtime/mgc.go:204 +0x25 fp=0xc000067fe0 sp=0xc000067fc8 pc=0x1aeac5
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x200561
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc000050fc0 m=nil [finalizer wait]:
runtime.gopark(0x22d4227ae28?, 0xc000028030?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc000057e20 sp=0xc000057e00 pc=0x1cffce
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:194 +0x107 fp=0xc000057fe0 sp=0xc000057e20 pc=0x1adba7
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x200561
created by runtime.createfing in goroutine 1
        C:/Program Files/Go/src/runtime/mfinal.go:164 +0x3d

goroutine 6 gp=0xc000051340 m=nil [IO wait]:
runtime.gopark(0xc00005d008?, 0xe9d420?, 0xa0?, 0x4c?, 0xc000074cd0?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc000069bf8 sp=0xc000069bd8 pc=0x1cffce
runtime.netpollblock(0x2f4?, 0x1988a6?, 0x0?)
        C:/Program Files/Go/src/runtime/netpoll.go:573 +0xf7 fp=0xc000069c30 sp=0xc000069bf8 pc=0x1c79b7
internal/poll.runtime_pollWait(0x22d6753af80, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:345 +0x85 fp=0xc000069c50 sp=0xc000069c30 pc=0x1fa5c5
internal/poll.(*pollDesc).wait(0x1aeed6?, 0xf53220?, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000069c78 sp=0xc000069c50 pc=0x2710a7
internal/poll.execIO(0xc000074ca0, 0xc000069d18)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe6 fp=0xc000069ce8 sp=0xc000069c78 pc=0x272586
internal/poll.(*FD).acceptOne(0xc000074c88, 0xb3c, {0xc0000b6000?, 0x22d674f17c8?, 0x20?}, 0x22d42270598?)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:944 +0x67 fp=0xc000069d48 sp=0xc000069ce8 pc=0x276c47
internal/poll.(*FD).Accept(0xc000074c88, 0xc000069ef8)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:978 +0x1bc fp=0xc000069e00 sp=0xc000069d48 pc=0x276f7c
net.(*netFD).accept(0xc000074c88)
        C:/Program Files/Go/src/net/fd_windows.go:178 +0x54 fp=0xc000069f18 sp=0xc000069e00 pc=0x37fc34
net.(*UnixListener).accept(0x1d9520?)
        C:/Program Files/Go/src/net/unixsock_posix.go:172 +0x16 fp=0xc000069f40 sp=0xc000069f18 pc=0x39b2f6
net.(*UnixListener).AcceptUnix(0xc0000232c0)
        C:/Program Files/Go/src/net/unixsock.go:247 +0x30 fp=0xc000069f70 sp=0xc000069f40 pc=0x399970
github.com/energye/energy/v2/pkgs/channel.(*browserChannel).accept(0xc00006c0f0)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:141 +0x2f fp=0xc000069fc8 sp=0xc000069f70 pc=0x3a3eef
github.com/energye/energy/v2/pkgs/channel.NewBrowser.gowrap1()
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:67 +0x25 fp=0xc000069fe0 sp=0xc000069fc8 pc=0x3a3885
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x200561
created by github.com/energye/energy/v2/pkgs/channel.NewBrowser in goroutine 1
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:67 +0x2d6

goroutine 7 gp=0xc000051a40 m=nil [IO wait]:
runtime.gopark(0xc000074fd0?, 0xc000074f50?, 0x60?, 0x4f?, 0xc0000afa90?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc0000afa20 sp=0xc0000afa00 pc=0x1cffce
runtime.netpollblock(0x1?, 0x1988a6?, 0x0?)
        C:/Program Files/Go/src/runtime/netpoll.go:573 +0xf7 fp=0xc0000afa58 sp=0xc0000afa20 pc=0x1c79b7
internal/poll.runtime_pollWait(0x22d6753ae88, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:345 +0x85 fp=0xc0000afa78 sp=0xc0000afa58 pc=0x1fa5c5
internal/poll.(*pollDesc).wait(0x0?, 0x22d674f33e8?, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc0000afaa0 sp=0xc0000afa78 pc=0x2710a7
internal/poll.execIO(0xc000074f20, 0x838778)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe6 fp=0xc0000afb10 sp=0xc0000afaa0 pc=0x272586
internal/poll.(*FD).ReadFrom(0xc000074f08, {0xc0002228e0, 0xc00000c0000afb18?, 0x1?})
        C:/Program Files/Go/src/internal/poll/fd_windows.go:579 +0x14f fp=0xc0000afb88 sp=0xc0000afb10 pc=0x27404f
net.(*netFD).readFrom(0xc000074f08, {0xc0002228e0?, 0xc0000afc40?, 0x3a3c91?})
        C:/Program Files/Go/src/net/fd_posix.go:61 +0x25 fp=0xc0000afbe0 sp=0xc0000afb88 pc=0x37de45
net.(*UnixConn).readFrom(0xc00005a078, {0xc0002228e0?, 0x22d42270a28?, 0x20?})
        C:/Program Files/Go/src/net/unixsock_posix.go:103 +0x27 fp=0xc0000afc40 sp=0xc0000afbe0 pc=0x39a967
net.(*UnixConn).ReadFromUnix(0xc00005a078, {0xc0002228e0?, 0x6bf2c0?, 0xc00009e001?})
        C:/Program Files/Go/src/net/unixsock.go:110 +0x30 fp=0xc0000afc90 sp=0xc0000afc40 pc=0x398a30
github.com/energye/energy/v2/pkgs/channel.(*channel).read(0x9c1ee0?, {0xc0002228e0?, 0x9c1d90?, 0xf52020?})
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel.go:304 +0x32 fp=0xc0000afcc0 sp=0xc0000afc90 pc=0x3a1e72
github.com/energye/energy/v2/pkgs/channel.(*channel).ipcRead(0xc00009c030)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel.go:362 +0x145 fp=0xc0000aff60 sp=0xc0000afcc0 pc=0x3a2525
github.com/energye/energy/v2/pkgs/channel.(*browserChannel).newConnection(0xc00006c0f0, {0x9c2310, 0xc00005a078})
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:202 +0x15c fp=0xc0000affb8 sp=0xc0000aff60 pc=0x3a41bc
github.com/energye/energy/v2/pkgs/channel.(*browserChannel).accept.gowrap1()
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:149 +0x28 fp=0xc0000affe0 sp=0xc0000affb8 pc=0x3a4028
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000affe8 sp=0xc0000affe0 pc=0x200561
created by github.com/energye/energy/v2/pkgs/channel.(*browserChannel).accept in goroutine 6
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:149 +0x115

goroutine 19 gp=0xc0000841c0 m=nil [IO wait]:
runtime.gopark(0xc0000b20d0?, 0xc0000b2050?, 0x60?, 0x20?, 0xc0000aba90?)
        C:/Program Files/Go/src/runtime/proc.go:402 +0xce fp=0xc0000aba20 sp=0xc0000aba00 pc=0x1cffce
runtime.netpollblock(0x1?, 0x1988a6?, 0x0?)
        C:/Program Files/Go/src/runtime/netpoll.go:573 +0xf7 fp=0xc0000aba58 sp=0xc0000aba20 pc=0x1c79b7
internal/poll.runtime_pollWait(0x22d6753ad90, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:345 +0x85 fp=0xc0000aba78 sp=0xc0000aba58 pc=0x1fa5c5
internal/poll.(*pollDesc).wait(0xc00009a0b0?, 0xc0000abaf0?, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc0000abaa0 sp=0xc0000aba78 pc=0x2710a7
internal/poll.execIO(0xc0000b2020, 0x838778)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe6 fp=0xc0000abb10 sp=0xc0000abaa0 pc=0x272586
internal/poll.(*FD).ReadFrom(0xc0000b2008, {0xc00008e8a0, 0xc00009c2a0?, 0xdf7448?})
        C:/Program Files/Go/src/internal/poll/fd_windows.go:579 +0x14f fp=0xc0000abb88 sp=0xc0000abb10 pc=0x27404f
net.(*netFD).readFrom(0xc0000b2008, {0xc00008e8a0?, 0xc0000abc40?, 0x3a3dda?})
        C:/Program Files/Go/src/net/fd_posix.go:61 +0x25 fp=0xc0000abbe0 sp=0xc0000abb88 pc=0x37de45
net.(*UnixConn).readFrom(0xc00009e018, {0xc00008e8a0?, 0x22d42270598?, 0x20?})
        C:/Program Files/Go/src/net/unixsock_posix.go:103 +0x27 fp=0xc0000abc40 sp=0xc0000abbe0 pc=0x39a967
net.(*UnixConn).ReadFromUnix(0xc00009e018, {0xc00008e8a0?, 0x6bf2c0?, 0xc00005a001?})
        C:/Program Files/Go/src/net/unixsock.go:110 +0x30 fp=0xc0000abc90 sp=0xc0000abc40 pc=0x398a30
github.com/energye/energy/v2/pkgs/channel.(*channel).read(0x9c1ee0?, {0xc00008e8a0?, 0x9c1d90?, 0xf52020?})
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel.go:304 +0x32 fp=0xc0000abcc0 sp=0xc0000abc90 pc=0x3a1e72
github.com/energye/energy/v2/pkgs/channel.(*channel).ipcRead(0xc0000232f0)
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel.go:362 +0x145 fp=0xc0000abf60 sp=0xc0000abcc0 pc=0x3a2525
github.com/energye/energy/v2/pkgs/channel.(*browserChannel).newConnection(0xc00006c0f0, {0x9c2310, 0xc00009e018})
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:202 +0x15c fp=0xc0000abfb8 sp=0xc0000abf60 pc=0x3a41bc
github.com/energye/energy/v2/pkgs/channel.(*browserChannel).accept.gowrap1()
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:149 +0x28 fp=0xc0000abfe0 sp=0xc0000abfb8 pc=0x3a4028
runtime.goexit({})
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x200561
created by github.com/energye/energy/v2/pkgs/channel.(*browserChannel).accept in goroutine 6
        C:/Users/JS/go/pkg/mod/github.com/energye/energy/v2@v2.3.6/pkgs/channel/channel_browser.go:149 +0x115
[ENERGY-Debug] 2024/02/27 13:41:41 IPC Read [Error] type: [unix] ChannelType: [client] Error: read unix @->C:\Users\JS\AppData\Local\Temp\energy.sock: wsarecvfrom: An existing connection was forcibly closed by the remote host.
[ENERGY-Debug] 2024/02/27 13:41:41 IPC Read Disconnect type: [unix] ChannelType: [client] processType: renderer
PS C:\Users\JS\Desktop\VSCode\chromium\chromium-118 2-3-6\examples>

plus some other problems:
1. The specified procedure could not be found. CEFAppConfig_SpecificVersion
2. LibVersion: is empty

**Comment by sxmxta** [comment]
@JSchmidt63 

Hello, I noticed that you should have upgraded to energy v2.3.6
But the liblcl. DLL you are using at this time should still be an old version, and you should upgrade it to match the energy release version
Note: Energy strictly matches the corresponding liblcl version library of the released version
The download address for liblcl corresponding to v2.3.6 is:
1. [liblcl sourceforge](https://sourceforge.net/projects/liblcl/files/v2.3.5/)
1. [liblcl site](https://energy.yanghy.cn/course/100/6364c5c2a749ba01d04ff485)

After upgrading, you will resolve this error and additional errors. Additionally, the LibVersion API may be removed in the future

**Comment by JSchmidt63** [comment]
Hello,

thank you so much. Now it worked. I love the this project.

Maybe you keep the LibVersion? So one get a hint that LibVersion is an old version and not fits to energy version.
Maybe it is even better to check libraries and throw a error.

Cheers

**Comment by sxmxta** [comment]
@JSchmidt63 
Thank you for your recognition
