### ISSUE TITLE
对于golang开箱即用，封装得很好！有几个问题请教一下：全屏问题、通过html弹窗问题、不能播放视频。

### ISSUE THREAD

**Issue by wflashy** [energye/energy#29]
以下是在Windows出现的问题
1. 全屏问题：Chromium().Fullscreen 和 Chromium().ExitFullscreen  这两个函数好像没有生效，不能全屏。
2. 通过html弹窗javascript:window.open()：使用的64位的Energy CEF 正常，32位的Energy CEF 就直接异常关闭程序。
3. 在html页面里不能播放视频。

**Comment by sxmxta** [comment]
你好
1. 全屏问题：参考 [frameless](https://github.com/energye/energy/tree/main/examples/frameless) 示例的使用方式.
 Chromium().Fullscreen, 不生效是因为：
 energy使用两种窗口模式
    一、默认使用的是LCL，我们自己管理窗口行为，并且对于窗口提供了大量的功能函数和属性直接使用。也支持大量的原生小部件。
    二、CEF的组件，ViewsFramework，简称 VF窗口，这种窗口模式可使用Chromium().Fullscreen相关函数控制

2. 弹窗：当前建议使用<a target="_blank">新窗口</a>方式，或者在Go代码中自己创建窗口，因为你可以控制大多数浏览器行为。[popup-sub-window](https://github.com/energye/energy/tree/main/examples/popup-sub-window)

3. 播放视频：CEF默认不支持视频播放，因为未公开 h264 编码，所以CEF提供编译的二进制框架包无法直接播放mp4等以h264编码的视频. [audio-video](https://github.com/energye/energy/tree/main/examples/audio-video)

另外：多参考示例，我大约写了60个左右示例程序。里面有常用的功能参考。

**Comment by MiyamuraMiyako** [comment]
> 你好
> 
>     1. 全屏问题：参考 [frameless](https://github.com/energye/energy/tree/main/examples/frameless) 示例的使用方式.
>        Chromium().Fullscreen, 不生效是因为：
>        energy使用两种窗口模式
>        一、默认使用的是LCL，我们自己管理窗口行为，并且对于窗口提供了大量的功能函数和属性直接使用。也支持大量的原生小部件。
>        二、CEF的组件，ViewsFramework，简称 VF窗口，这种窗口模式可使用Chromium().Fullscreen相关函数控制
> 
>     2. 弹窗：当前建议使用新窗口方式，或者在Go代码中自己创建窗口，因为你可以控制大多数浏览器行为。[popup-sub-window](https://github.com/energye/energy/tree/main/examples/popup-sub-window)
> 
>     3. 播放视频：CEF默认不支持视频播放，因为未公开 h264 编码，所以CEF提供编译的二进制框架包无法直接播放mp4等以h264编码的视频. [audio-video](https://github.com/energye/energy/tree/main/examples/audio-video)
> 
> 
> 另外：多参考示例，我大约写了60个左右示例程序。里面有常用的功能参考。

@sxmxta 你好，请问：
在Linux Aarch64（debian 11 xfce desktop）中，我尝试了修改窗体x=0，y=0；x，w为屏幕的最大分辨率，或是调用`window.Fullscreen()`或 `window.Chromium().Fullscreen()`，都未能成功全屏（顶部和底部桌面管理器的界面仍会露出）。
不知道这是我调用方法问题还是库的内部实现问题。
顶部：
![图片](https://github.com/user-attachments/assets/c5ef3519-7704-4d88-957f-0f9b3b648201)
底部：
![图片](https://github.com/user-attachments/assets/2177a0c4-1013-4ac3-b3d9-89eb17be16c0)

**Comment by MiyamuraMiyako** [comment]
似乎只有这样才有效`cef.BrowserWindow.Config.WindowInitState = types.WsFullScreen`，其它各种设置均有尝试都不生效。

**Comment by coyzeng** [comment]
> 你好
> 
> 1. 全屏问题：参考 [frameless](https://github.com/energye/energy/tree/main/examples/frameless) 示例的使用方式.
>    Chromium().Fullscreen, 不生效是因为：
>    energy使用两种窗口模式
>    一、默认使用的是LCL，我们自己管理窗口行为，并且对于窗口提供了大量的功能函数和属性直接使用。也支持大量的原生小部件。
>    二、CEF的组件，ViewsFramework，简称 VF窗口，这种窗口模式可使用Chromium().Fullscreen相关函数控制
> 2. 弹窗：当前建议使用新窗口方式，或者在Go代码中自己创建窗口，因为你可以控制大多数浏览器行为。[popup-sub-window](https://github.com/energye/energy/tree/main/examples/popup-sub-window)
> 3. 播放视频：CEF默认不支持视频播放，因为未公开 h264 编码，所以CEF提供编译的二进制框架包无法直接播放mp4等以h264编码的视频. [audio-video](https://github.com/energye/energy/tree/main/examples/audio-video)
> 
> 另外：多参考示例，我大约写了60个左右示例程序。里面有常用的功能参考。

这个视频播放怎么处理，要换自己编译的CEF版本吗
