### ISSUE TITLE
operations in the BrowserWindow showing delayed

### ISSUE THREAD

**Issue by Edward923** [energye/energy#8]
operating dialog / drawer / menu-page showing delayed ...

**Comment by sxmxta** [comment]
I need to take a look at the dynamic effect diagram
Or an example or address used

**Comment by Edward923** [comment]
cef.BrowserWindow.Config.Url = "https://pro.eleadmin.com/"
 and like this

**Comment by sxmxta** [comment]
@Edward923 

Enable GPU acceleration option

`
appCfg := cef.NewApplicationConfig()
appCfg.SetEnableGPU(true) // open gpu acceleration 
cefApp := cef.NewApplication(appCfg)

`

**Comment by Edward923** [comment]
so much 3Q!!!
